server:
  port: 0
spring:
  application:
    name: chetax-service3
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8849
        namespace: public
    sentinel:
      eager: true #Sentinel 控制台地址
      transport: 
        dashboard: localhost:7777 #取消Sentinel控制台懒加载
feign:
  sentinel:
    enabled: true
  client: 
    config:  
      default: 
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
