server:
  port: 0
spring:
  application:
    name: matrix-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: 'http://localhost:9098/matrix-security/rsa/publicKey'
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8849
        namespace: public
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8091
#        client-ip: 127.0.0.1
#        port: 8091
#      eager: true  
    gateway: 
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: service1
        uri: lb://matrix-service1
        predicates:
        - Path=/service1/**
        filters:
        - StripPrefix=1
      - id: service2
        uri: lb://matrix-service2
        predicates:
        - Path=/service2/**
        filters:
        - StripPrefix=1 
      - id: matrix-security
        uri: lb://matrix-security
        predicates:
        - Path=/matrix-security/**
        filters:
        - StripPrefix=1   
#security:
#  basic: false
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9098/users/current
#    client:
#      client-id: client1
#      client-secret: 123456
#      access-token-uri: http://localhost:9098/oauth/token
#      user-authorization-uri: http://localhost:9098/oauth/authorize
#      grant-type: client_credentials,password
#      scope: server
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      enabled: true 
# 配置白名单路径
white-list:
    urls:
      - "/matrix-security/oauth/token"
      - "/matrix-security/rsa/publicKey"
      