server:
  port: 0
spring:
  application:
    name: matrix-service2
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8849
        namespace: public
security:
  basic: false
  oauth2:
    resource:
      user-info-uri: http://localhost:9098/users/current
    client:
      client-id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9098/oauth/token
      user-authorization-uri: http://localhost:9098/oauth/authorize
      grant-type: client_credentials,password
      scope: server
feign:
 client: 
   config:  
     default: 
       connect-timeout: 5000
       read-timeout: 5000
       logger-level: full