server:
  port: 0
spring:
  application:
    name: chetax-kafka
  #是否开启kafka（非spring-cloud-stream配置）
  kafka:
    enabled: false
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8849
        namespace: public
    stream:
      kafka:
        binder:
          #172.*.*.6:9092,172.*.*.7:9092,172.*.*.8:9092
          brokers: 127.0.0.1:9092
          #172.*.*.6:2181,172.*.*.7:2181,172.*.*.8:2181
          zkNodes: 127.0.0.1:2181
          requiredAcks: 1
      bindings:
        #缺省的输入通道
        es_default_input: 
          destination: es_default_topic
          binder: kafka
          group: es_default_group
          consumer: 
            #入站消费者的并发性
            concurrency: 2
        #缺省的输出通道
        es_default_output:
          destination: es_default_topic
          binder: kafka
        #告警的输入通道（多主题、分组测试用，实际开发中根据业务需求定义）
        es_alarm_input:
          destination: es_alarm_topic
          binder: kafka
          group: es_alarm_group
        #告警的输出通道（多主题、分组测试用，实际开发中根据业务需求定义）
        es_alarm_output:
          destination: es_alarm_topic
          binder: kafka  

